/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package IGU;

import IGU.Invitado.pAsignaturas;
import IGU.Invitado.pCursos;
import Logica.App;
import Logica.MYSQL;
import java.awt.Color;
import Logica.Usuarios.Acciones.Invitado;

/**
 *
 * @author yepez
 */
public class frmInvitado extends javax.swing.JFrame {

    /**
     * Creates new form frmInvitado
     */
    private Invitado inv = new Invitado();
    
    public frmInvitado() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    int xMouse, yMouse;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pCabeza = new javax.swing.JPanel();
        pSalir = new javax.swing.JPanel();
        lbSalir = new javax.swing.JLabel();
        pSesion = new javax.swing.JPanel();
        lbCerrarSesion = new javax.swing.JLabel();
        pBotones = new javax.swing.JPanel();
        pCursos = new javax.swing.JPanel();
        txtDo = new javax.swing.JLabel();
        pAsignaturas = new javax.swing.JPanel();
        txtEs = new javax.swing.JLabel();
        pAccion = new javax.swing.JPanel();
        bg = new javax.swing.JPanel();
        bgImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(1024, 576));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pCabeza.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        pCabeza.setOpaque(false);
        pCabeza.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pCabezaMouseDragged(evt);
            }
        });
        pCabeza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pCabezaMousePressed(evt);
            }
        });

        pSalir.setBackground(new java.awt.Color(238, 238, 238));
        pSalir.setPreferredSize(new java.awt.Dimension(30, 25));

        lbSalir.setBackground(new java.awt.Color(238, 238, 238));
        lbSalir.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbSalir.setForeground(new java.awt.Color(0, 0, 0));
        lbSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSalir.setText("X");
        lbSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbSalir.setPreferredSize(new java.awt.Dimension(30, 25));
        lbSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbSalirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pSalirLayout = new javax.swing.GroupLayout(pSalir);
        pSalir.setLayout(pSalirLayout);
        pSalirLayout.setHorizontalGroup(
            pSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(pSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pSalirLayout.setVerticalGroup(
            pSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(pSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pSesion.setBackground(new java.awt.Color(204, 204, 204));

        lbCerrarSesion.setBackground(new java.awt.Color(238, 238, 238));
        lbCerrarSesion.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        lbCerrarSesion.setForeground(new java.awt.Color(0, 0, 0));
        lbCerrarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCerrarSesion.setText("Cerrar Sesión");
        lbCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbCerrarSesion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbCerrarSesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbCerrarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbCerrarSesionMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pSesionLayout = new javax.swing.GroupLayout(pSesion);
        pSesion.setLayout(pSesionLayout);
        pSesionLayout.setHorizontalGroup(
            pSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pSesionLayout.setVerticalGroup(
            pSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout pCabezaLayout = new javax.swing.GroupLayout(pCabeza);
        pCabeza.setLayout(pCabezaLayout);
        pCabezaLayout.setHorizontalGroup(
            pCabezaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pCabezaLayout.createSequentialGroup()
                .addGap(0, 888, Short.MAX_VALUE)
                .addComponent(pSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pCabezaLayout.setVerticalGroup(
            pCabezaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCabezaLayout.createSequentialGroup()
                .addGroup(pCabezaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(pCabeza, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, 25));

        pBotones.setOpaque(false);
        pBotones.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 20));

        pCursos.setBackground(new java.awt.Color(215, 35, 35));
        pCursos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pCursos.setPreferredSize(new java.awt.Dimension(240, 40));
        pCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pCursosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pCursosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pCursosMouseExited(evt);
            }
        });
        pCursos.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 10));

        txtDo.setBackground(new java.awt.Color(246, 246, 246));
        txtDo.setFont(new java.awt.Font("KG Red Hands", 0, 14)); // NOI18N
        txtDo.setForeground(new java.awt.Color(255, 255, 255));
        txtDo.setText("CURSOS");
        pCursos.add(txtDo);

        pBotones.add(pCursos);

        pAsignaturas.setBackground(new java.awt.Color(215, 35, 35));
        pAsignaturas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pAsignaturas.setPreferredSize(new java.awt.Dimension(240, 40));
        pAsignaturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pAsignaturasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pAsignaturasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pAsignaturasMouseExited(evt);
            }
        });
        pAsignaturas.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 10));

        txtEs.setBackground(new java.awt.Color(246, 246, 246));
        txtEs.setFont(new java.awt.Font("KG Red Hands", 0, 14)); // NOI18N
        txtEs.setForeground(new java.awt.Color(255, 255, 255));
        txtEs.setText("ASIGNATURAS");
        pAsignaturas.add(txtEs);

        pBotones.add(pAsignaturas);

        getContentPane().add(pBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 252, 435));

        pAccion.setOpaque(false);

        javax.swing.GroupLayout pAccionLayout = new javax.swing.GroupLayout(pAccion);
        pAccion.setLayout(pAccionLayout);
        pAccionLayout.setHorizontalGroup(
            pAccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 772, Short.MAX_VALUE)
        );
        pAccionLayout.setVerticalGroup(
            pAccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 546, Short.MAX_VALUE)
        );

        getContentPane().add(pAccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 30, 772, 546));

        bg.setPreferredSize(new java.awt.Dimension(1024, 576));

        bgImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IGU/IMG/Invitado.png"))); // NOI18N

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bgImg, javax.swing.GroupLayout.PREFERRED_SIZE, 1024, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bgImg, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, 576));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pCursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pCursosMouseClicked
        inv.showPanel(new pCursos(), pAccion);
    }//GEN-LAST:event_pCursosMouseClicked

    private void pCursosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pCursosMouseEntered
        pCursos.setBackground(new Color(197, 0, 0));
    }//GEN-LAST:event_pCursosMouseEntered

    private void pCursosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pCursosMouseExited
        pCursos.setBackground(new Color(215, 35, 35));
    }//GEN-LAST:event_pCursosMouseExited

    private void pAsignaturasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pAsignaturasMouseClicked
        inv.showPanel(new pAsignaturas(), pAccion);
    }//GEN-LAST:event_pAsignaturasMouseClicked

    private void pAsignaturasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pAsignaturasMouseEntered
        pAsignaturas.setBackground(new Color(197, 0, 0));
    }//GEN-LAST:event_pAsignaturasMouseEntered

    private void pAsignaturasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pAsignaturasMouseExited
        pAsignaturas.setBackground(new Color(215, 35, 35));
    }//GEN-LAST:event_pAsignaturasMouseExited

    private void lbSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSalirMouseClicked
        new MYSQL().desconectar();
        new App();
        App.deleteTempFile();
        System.exit(0);
    }//GEN-LAST:event_lbSalirMouseClicked

    private void lbSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSalirMouseEntered
        pSalir.setBackground(Color.red);
    }//GEN-LAST:event_lbSalirMouseEntered

    private void lbSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSalirMouseExited
        pSalir.setBackground(new Color(238, 238, 238));
    }//GEN-LAST:event_lbSalirMouseExited

    private void lbCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCerrarSesionMouseClicked
        this.dispose();
        new MYSQL().desconectar();
        new frmLogin().setVisible(true);
    }//GEN-LAST:event_lbCerrarSesionMouseClicked

    private void lbCerrarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCerrarSesionMouseEntered
        pSesion.setBackground(Color.red);
    }//GEN-LAST:event_lbCerrarSesionMouseEntered

    private void lbCerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCerrarSesionMouseExited
        pSesion.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_lbCerrarSesionMouseExited

    private void pCabezaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pCabezaMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_pCabezaMouseDragged

    private void pCabezaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pCabezaMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_pCabezaMousePressed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel bgImg;
    private javax.swing.JLabel lbCerrarSesion;
    private javax.swing.JLabel lbSalir;
    private javax.swing.JPanel pAccion;
    private javax.swing.JPanel pAsignaturas;
    private javax.swing.JPanel pBotones;
    private javax.swing.JPanel pCabeza;
    private javax.swing.JPanel pCursos;
    private javax.swing.JPanel pSalir;
    private javax.swing.JPanel pSesion;
    private javax.swing.JLabel txtDo;
    private javax.swing.JLabel txtEs;
    // End of variables declaration//GEN-END:variables
}
