/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package IGU.Estudiante;

import Logica.Modelo.IdUsuario;
import Logica.Modelo.Usuario;
import Logica.Usuarios.Acciones.Estudiante;
import Logica.Usuarios.Administradores;
import javax.swing.DefaultListModel;

/**
 *
 * @author Edwin Lopez
 */
public class pNotasA extends javax.swing.JPanel {

    /**
     * Creates new form pNotasA
     */
    private DefaultListModel modelo1 = new DefaultListModel();
    private Estudiante es = new Estudiante();
    private IdUsuario idu = Usuario.idU;
    private Administradores admin = new Administradores();

    public pNotasA() {
        initComponents();
        this.lista();
        this.tabla();
    }

    private void lista() {
        ltAsignaturas.setModel(modelo1);
        modelo1.removeAllElements();

        for (int i = 0; i < es.matriculado(this.idu.getId()).size(); i++) {
            modelo1.addElement(es.matriculado(this.idu.getId()).get(i));
        }

    }

    private void tabla() {
        String n = ltAsignaturas.getSelectedValue();
        this.admin.setId("asignaturas", n);
        es.tareasCalificadas(tbNotas, idu.getId(), this.admin.getId());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        ltAsignaturas = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbNotas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(772, 546));
        setPreferredSize(new java.awt.Dimension(772, 546));

        ltAsignaturas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ltAsignaturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ltAsignaturasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ltAsignaturas);

        tbNotas = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tbNotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbNotas.getTableHeader().setResizingAllowed(false);
        tbNotas.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbNotas);

        jLabel1.setText("SELECCIONE UNA ASIGNATURA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                        .addGap(76, 76, 76)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(50, 50, 50))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ltAsignaturasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ltAsignaturasMouseClicked
        if (!es.matriculado(this.idu.getId()).isEmpty()) {
            this.tabla();
        }
    }//GEN-LAST:event_ltAsignaturasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> ltAsignaturas;
    private javax.swing.JTable tbNotas;
    // End of variables declaration//GEN-END:variables
}
