/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package IGU.Docente;

import Logica.Modelo.IdUsuario;
import Logica.Modelo.Usuario;
import Logica.Usuarios.Acciones.Docente;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Edwin Lopez
 */
public class pCursos extends javax.swing.JPanel {

    private Docente doc = new Docente();
    private IdUsuario idu = Usuario.idU;
    
    /**
     * Creates new form pCursos
     */
    public pCursos() {
        initComponents();
        doc.getCursosAsignaturas(tbCA, idu.getId());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbCA = new javax.swing.JTable();

        setMinimumSize(new java.awt.Dimension(772, 546));
        setPreferredSize(new java.awt.Dimension(772, 546));

        tbCA = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tbCA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbCA.getTableHeader().setResizingAllowed(false);
        tbCA.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbCA);
        if (tbCA.getColumnModel().getColumnCount() > 0) {
            tbCA.getColumnModel().getColumn(0).setResizable(false);
            tbCA.getColumnModel().getColumn(1).setResizable(false);
            tbCA.getColumnModel().getColumn(2).setResizable(false);
            tbCA.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbCA;
    // End of variables declaration//GEN-END:variables
}
