/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package IGU.Docente;

import Logica.Modelo.IdUsuario;
import Logica.Modelo.Usuario;
import Logica.Usuarios.Acciones.Docente;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Edwin Lopez
 */
public class pListado extends javax.swing.JPanel {

    /**
     * Creates new form pListado
     */
    private Docente doc = new Docente();
    private IdUsuario idu = Usuario.idU;
    private DefaultComboBoxModel modelo = new DefaultComboBoxModel();
    private DefaultComboBoxModel modelo1 = new DefaultComboBoxModel();
    private int ida;
    private int idc;

    public int getIda() {
        return this.ida;
    }

    public void setIda(int ida) {
        this.ida = ida;
    }

    public int getIdc() {
        return this.idc;
    }

    public void setIdc(int idc) {
        this.idc = idc;
    }
    
    public pListado(int idU) {
        initComponents();
        this.asignaturas();
        this.cursos();
        this.llenarTabla();
    }
    
    private void asignaturas(){
        cbAsignaturas.setModel(modelo);
        modelo.removeAllElements();
        for (int i = 0; i < doc.getAsignaturas(idu.getId()).size(); i++) {
            modelo.addElement(doc.getAsignaturas(idu.getId()).get(i));
        }
    }
    
    public void cursos(){
        cbCursos.setModel(modelo1);
        modelo1.removeAllElements();
        this.setIda(doc.getIdTablas("asignaturas",cbAsignaturas.getSelectedItem().toString()));
        for (int i = 0; i < doc.getCursos(idu.getId(),this.getIda()).size(); i++) {
            modelo1.addElement(doc.getCursos(idu.getId(),this.getIda()).get(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbLista = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        cbAsignaturas = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cbCursos = new javax.swing.JComboBox<>();
        btnFiltro = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(772, 546));

        tbLista = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tbLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbLista.getTableHeader().setResizingAllowed(false);
        tbLista.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbLista);
        if (tbLista.getColumnModel().getColumnCount() > 0) {
            tbLista.getColumnModel().getColumn(0).setResizable(false);
            tbLista.getColumnModel().getColumn(1).setResizable(false);
            tbLista.getColumnModel().getColumn(2).setResizable(false);
            tbLista.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel5.setText("Asignatura");

        cbAsignaturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAsignaturasActionPerformed(evt);
            }
        });

        jLabel4.setText("Cursos");

        cbCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCursosActionPerformed(evt);
            }
        });

        btnFiltro.setText("Filtrar");
        btnFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbAsignaturas, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btnFiltro)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbAsignaturas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnFiltro)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbAsignaturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAsignaturasActionPerformed
        this.cursos();
    }//GEN-LAST:event_cbAsignaturasActionPerformed

    private void cbCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCursosActionPerformed

    }//GEN-LAST:event_cbCursosActionPerformed

    private void btnFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltroActionPerformed
        if (!doc.getCursos(idu.getId(),this.getIda()).isEmpty()) {
        this.llenarTabla();    
        }else{
            JOptionPane.showMessageDialog(null, "No se puede filtar el listado de estudiantes,\npor que la asignatura seleccionada\nno tiene un curso definido");
        }
        
    }//GEN-LAST:event_btnFiltroActionPerformed

    public void llenarTabla(){
        this.setIdc(doc.getIdTablas("cursos",cbCursos.getSelectedItem().toString()));
        doc.listaEstudiantes(tbLista, this.getIdc(), this.getIda());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFiltro;
    private javax.swing.JComboBox<String> cbAsignaturas;
    private javax.swing.JComboBox<String> cbCursos;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbLista;
    // End of variables declaration//GEN-END:variables
}
