/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package IGU.Administrador;

import Logica.Usuarios.Acciones.Administrador;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Edwin Lopez
 */
public class pAsignarDocentes extends javax.swing.JPanel {

    /**
     * Creates new form pAsignarDocentes
     */
    private DefaultListModel modelo = new DefaultListModel();
    private DefaultListModel modelo1 = new DefaultListModel();
    private Administrador admin = new Administrador();
    private int vDocente;
    private int vAsignatura;

    public int getvDocente() {
        return this.vDocente;
    }

    public void setvDocente(int vDocente) {
        this.vDocente = vDocente;
    }

    public int getvAsignatura() {
        return this.vAsignatura;
    }

    public void setvAsignatura(int vAsignatura) {
        this.vAsignatura = vAsignatura;
    }

    public pAsignarDocentes() {
        initComponents();
        this.listaD();
        this.listaA();
        this.admin.getAsignacion(tbDatos);
    }

    private void listaA() {
        ltAsignaturas.setModel(modelo);
        modelo.removeAllElements();

        for (int i = 0; i < admin.getAsignaturas().size(); i++) {
            modelo.addElement(admin.getAsignaturas().get(i));
        }

    }

    private void listaD() {
        ltDocentes.setModel(modelo1);
        modelo1.removeAllElements();

        for (int i = 0; i < admin.getUsuariosTipo("= 2").size(); i++) {
            modelo1.addElement(admin.getUsuariosTipo("= 2").get(i));
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ltDocentes = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        ltAsignaturas = new javax.swing.JList<>();
        btnAsignar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbDatos = new javax.swing.JTable();
        btnDesvincular = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setMinimumSize(new java.awt.Dimension(772, 546));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ltDocentes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ltDocentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ltDocentesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ltDocentes);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 75, 183, 330));

        ltAsignaturas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ltAsignaturas.setEnabled(false);
        ltAsignaturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ltAsignaturasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ltAsignaturas);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 75, 169, 330));

        btnAsignar.setText("Asignar");
        btnAsignar.setEnabled(false);
        btnAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarActionPerformed(evt);
            }
        });
        add(btnAsignar, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 434, -1, -1));

        tbDatos = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tbDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbDatos.getTableHeader().setResizingAllowed(false);
        tbDatos.getTableHeader().setReorderingAllowed(false);
        tbDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDatosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbDatos);
        if (tbDatos.getColumnModel().getColumnCount() > 0) {
            tbDatos.getColumnModel().getColumn(0).setResizable(false);
            tbDatos.getColumnModel().getColumn(1).setResizable(false);
        }

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 42, 295, -1));

        btnDesvincular.setText("Desvincular");
        btnDesvincular.setEnabled(false);
        btnDesvincular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesvincularActionPerformed(evt);
            }
        });
        add(btnDesvincular, new org.netbeans.lib.awtextra.AbsoluteConstraints(571, 481, -1, -1));

        jLabel1.setText("SELECCIONE UN DOCENTE:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 53, -1, -1));

        jLabel2.setText("SELECCIONE UNA ASIGNATURA");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 53, -1, -1));

        jLabel3.setText("PREVISUALIZACION DE LAS ASIGNACIONES");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 20, -1, -1));

        jPanel1.setOpaque(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 530, 30, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarActionPerformed
        if (this.admin.getIdT() != 0) {
            if (this.admin.getId() != 0) {
                this.admin.asignarDocentes();
                this.listaA();
                this.listaD();
                this.admin.getAsignacion(tbDatos);
            } else {
                JOptionPane.showMessageDialog(null, "Por favor seleccione una asignatura");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Por favor seleccione un docente");
        }
    }//GEN-LAST:event_btnAsignarActionPerformed

    private void ltDocentesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ltDocentesMouseClicked
        if (!admin.getUsuariosTipo("= 2").isEmpty()) {
            String n = ltDocentes.getSelectedValue();
            this.admin.setIdT(n);
            ltAsignaturas.setEnabled(true);
        }
    }//GEN-LAST:event_ltDocentesMouseClicked

    private void ltAsignaturasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ltAsignaturasMouseClicked
        if (!admin.getAsignaturas().isEmpty()) {
            if (ltAsignaturas.isEnabled()) {
                String n = ltAsignaturas.getSelectedValue();
                this.admin.setId("asignaturas", n);
                btnAsignar.setEnabled(true);
            }
        }
    }//GEN-LAST:event_ltAsignaturasMouseClicked

    private void btnDesvincularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesvincularActionPerformed
        if (0 == JOptionPane.showConfirmDialog(null, "Estas seguro de realizar esta accion, no habra marcha atras")) {
            this.admin.desvincularDocentes(this.getvAsignatura(), this.getvDocente());
        }
    }//GEN-LAST:event_btnDesvincularActionPerformed

    private void tbDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDatosMouseClicked
        btnDesvincular.setEnabled(true);
        int fila = tbDatos.getSelectedRow();

        String temp = tbDatos.getValueAt(fila, 0).toString();
        this.admin.setIdT(temp);
        this.setvDocente(this.admin.getIdT());

        String temp1 = tbDatos.getValueAt(fila, 1).toString();
        this.admin.setId("asignaturas", temp1);
        this.setvAsignatura(this.admin.getId());
    }//GEN-LAST:event_tbDatosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignar;
    private javax.swing.JButton btnDesvincular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> ltAsignaturas;
    private javax.swing.JList<String> ltDocentes;
    private javax.swing.JTable tbDatos;
    // End of variables declaration//GEN-END:variables
}
