/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package IGU.Administrador;

import Logica.Usuarios.Acciones.Administrador;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Edwin Lopez
 */
public class pCRUD_Cursos extends javax.swing.JPanel {

    /**
     * Creates new form pCRUD_Cursos
     */
    private Administrador admin = new Administrador();
    private int vCursos, vAsignaturas;

    public int getvCursos() {
        return this.vCursos;
    }

    public void setvCursos(int vCursos) {
        this.vCursos = vCursos;
    }

    public int getvAsignaturas() {
        return this.vAsignaturas;
    }

    public void setvAsignaturas(int vAsignaturas) {
        this.vAsignaturas = vAsignaturas;
    }

    public pCRUD_Cursos() {
        initComponents();
        tbCursos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        this.admin.actualizarTablaCursos("cursos", tbCursos);
        this.admin.tablaUnida(tbCursosAsignaturas);
        btnMod.setEnabled(false);
        btnEliminar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnCrear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCursos = new javax.swing.JTable();
        btnMod = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbAsignaturas = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbCursosAsignaturas = new javax.swing.JTable();
        btnUnir = new javax.swing.JButton();
        btnDesvincular = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(772, 546));

        jLabel1.setText("Nombre");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        tbCursos = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tbCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbCursos.getTableHeader().setResizingAllowed(false);
        tbCursos.getTableHeader().setReorderingAllowed(false);
        tbCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbCursosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbCursos);
        if (tbCursos.getColumnModel().getColumnCount() > 0) {
            tbCursos.getColumnModel().getColumn(0).setResizable(false);
        }

        btnMod.setText("Modificar");
        btnMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        tbAsignaturas = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tbAsignaturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Asignaturas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbAsignaturas.setEnabled(false);
        tbAsignaturas.getTableHeader().setResizingAllowed(false);
        tbAsignaturas.getTableHeader().setReorderingAllowed(false);
        tbAsignaturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbAsignaturasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbAsignaturas);
        if (tbAsignaturas.getColumnModel().getColumnCount() > 0) {
            tbAsignaturas.getColumnModel().getColumn(0).setResizable(false);
        }

        tbCursosAsignaturas = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tbCursosAsignaturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbCursosAsignaturas.getTableHeader().setResizingAllowed(false);
        tbCursosAsignaturas.getTableHeader().setReorderingAllowed(false);
        tbCursosAsignaturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbCursosAsignaturasMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbCursosAsignaturas);
        if (tbCursosAsignaturas.getColumnModel().getColumnCount() > 0) {
            tbCursosAsignaturas.getColumnModel().getColumn(0).setResizable(false);
            tbCursosAsignaturas.getColumnModel().getColumn(1).setResizable(false);
        }

        btnUnir.setText("Asignar");
        btnUnir.setEnabled(false);
        btnUnir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnirActionPerformed(evt);
            }
        });

        btnDesvincular.setText("Desvincular");
        btnDesvincular.setEnabled(false);
        btnDesvincular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesvincularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCrear)
                    .addComponent(btnEliminar)
                    .addComponent(btnMod))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(btnUnir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDesvincular)
                .addGap(99, 99, 99))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(btnCrear)
                        .addGap(18, 18, 18)
                        .addComponent(btnMod)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUnir)
                    .addComponent(btnDesvincular))
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        if (txtNombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe llenar los campos habilitados");
        } else {
            if (admin.validarAC("cursos", txtNombre.getText())) {
                this.admin.setNombre(txtNombre.getText());
                this.admin.crearCursos("cursos");
                txtNombre.setText("");
                this.admin.actualizarTablaCursos("cursos", tbCursos);
            } else {
                JOptionPane.showMessageDialog(null, "Ya existe ese curso");
            }
        }
    }//GEN-LAST:event_btnCrearActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        char validar = evt.getKeyChar();
        if (!Character.isLetterOrDigit(validar)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void tbCursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbCursosMouseClicked
        int fila = tbCursos.getSelectedRow();
        txtNombre.setText(tbCursos.getValueAt(fila, 0).toString());
        this.admin.setId("cursos", txtNombre.getText());
        this.admin.getAsignaturasSCurso(tbAsignaturas);
        this.setvCursos(this.admin.getId());
        this.tbAsignaturas.setEnabled(true);
        btnCrear.setEnabled(false);
        btnMod.setEnabled(true);
        btnEliminar.setEnabled(true);
    }//GEN-LAST:event_tbCursosMouseClicked

    private void btnModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModActionPerformed
        if (txtNombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe llenar los campos habilitados");
        } else {
            if (admin.validarAC("cursos", txtNombre.getText())) {

                this.admin.setNombre(txtNombre.getText());
                this.admin.modificarCurso("cursos");
                txtNombre.setText("");
                this.admin.actualizarTablaCursos("cursos", tbCursos);
                btnCrear.setEnabled(true);
                btnMod.setEnabled(false);
                btnEliminar.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(null, "Ya existe ese curso");

            }
        }
    }//GEN-LAST:event_btnModActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (0 == JOptionPane.showConfirmDialog(null, "Estas seguro de realizar esta accion, no habra marcha atras")) {
            this.admin.eliminarCA("cursos");
            this.admin.actualizarTablaCursos("cursos", tbCursos);
        }
        txtNombre.setText("");
        btnCrear.setEnabled(true);
        btnMod.setEnabled(false);
        btnEliminar.setEnabled(false);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnUnirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnirActionPerformed
        this.admin.setAsigntauraCurso(vCursos, vAsignaturas);
        this.admin.tablaUnida(tbCursosAsignaturas);
    }//GEN-LAST:event_btnUnirActionPerformed

    private void tbAsignaturasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbAsignaturasMouseClicked
        btnUnir.setEnabled(true);
        int fila = tbAsignaturas.getSelectedRow();

        String temp = tbAsignaturas.getValueAt(fila, 0).toString();
        this.admin.setId("asignaturas", temp);
        this.setvAsignaturas(this.admin.getId());

    }//GEN-LAST:event_tbAsignaturasMouseClicked

    private void tbCursosAsignaturasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbCursosAsignaturasMouseClicked
        btnDesvincular.setEnabled(true);
        btnUnir.setEnabled(false);
        
        int fila = tbCursosAsignaturas.getSelectedRow();

        String temp = tbCursosAsignaturas.getValueAt(fila, 0).toString();
        this.admin.setId("cursos", temp);
        this.setvCursos(this.admin.getId());

        String temp1 = tbCursosAsignaturas.getValueAt(fila, 1).toString();
        this.admin.setId("asignaturas", temp1);
        this.setvAsignaturas(this.admin.getId());
        this.admin.actualizarTablaCursos("cursos", tbCursos);
    }//GEN-LAST:event_tbCursosAsignaturasMouseClicked

    private void btnDesvincularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesvincularActionPerformed
        if (0 == JOptionPane.showConfirmDialog(null, "Estas seguro de realizar esta accion, no habra marcha atras")) {
            this.admin.desvincularAC(this.getvAsignaturas(), this.getvCursos());
        }
        this.admin.tablaUnida(tbCursosAsignaturas);
        this.admin.actualizarTablaCursos("cursos", tbCursos);
        btnDesvincular.setEnabled(false);
    }//GEN-LAST:event_btnDesvincularActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnDesvincular;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnMod;
    private javax.swing.JButton btnUnir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tbAsignaturas;
    private javax.swing.JTable tbCursos;
    private javax.swing.JTable tbCursosAsignaturas;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
